name: ifeedapp
channels:
  - dsdale24
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2_cffi=19.1.0
  - asn1crypto=1.2.*
  - backcall=0.1.*
  - bcrypt=3.1.*
  - blas=1.0
  - branca=0.3.*
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.*
  - click=7.0
  - conda=4.7.*
  - conda-package-handling=1.6.*
  - cryptography=2.8
  - cyrus-sasl=2.1.*
  - decorator=4.4.*
  - flask=1.1.*
  - flask-script=2.0.*
  - folium=0.10.1
  - geojson=2.5.*
  - idna=2.8
  - intel-openmp=2019.4
  - ipython=7.7.*
  - ipython_genutils=0.2.*
  - itsdangerous=1.1.*
  - jedi=0.15.1
  - jinja2=2.10.*
  - krb5=1.16.*
  - libdb=6.1.*
  - libedit=3.1.20181209
  - libffi=3.2.*
  - libgcc-ng=9.1.*
  - libgfortran-ng=7.3.*
  - libntlm=1.5
  - libprotobuf=3.6.*
  - libsolv=0.7.*
  - libstdcxx-ng=9.1.*
  - mamba=0.1.*
  - markupsafe=1.1.*
  - mkl=2019.4
  - mkl-service=2.3.*
  - mkl_fft=1.0.*
  - mkl_random=1.1.0
  - mysql=5.7.*
  - mysql-connector-c=6.1.*
  - mysql-connector-python=8.0.*
  - ncurses=6.1
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openssl=1.1.*
  - pandas=0.25.0
  - parso=0.5.*
  - passlib=1.7.*
  - pexpect=4.7.*
  - pickleshare=0.7.*
  - pip=19.3.*
  - prompt_toolkit=2.0.*
  - protobuf=3.6.*
  - ptyprocess=0.6.*
  - pycosat=0.6.*
  - pycparser=2.19
  - pygments=2.5.*
  - pymemcache=2.2.*
  - pyopenssl=19.1.*
  - pysocks=1.7.*
  - python=3.7.*
  - python-dateutil=2.8.*
  - pytz=2019.3
  - qt5=5.3.*
  - readline=7.0
  - requests=2.22.0
  - ruamel_yaml=0.15.87
  - setuptools=42.0.*
  - six=1.13.0
  - sqlite=3.29.0
  - tk=8.6.*
  - tqdm=4.40.2
  - traitlets=4.3.*
  - urllib3=1.24.2
  - vincent=0.4.*
  - wcwidth=0.1.*
  - werkzeug=0.16.0
  - wheel=0.33.6
  - wtforms=2.2.*
  - xz=5.2.*
  - yaml=0.1.*
  - zlib=1.2.*
  - pip:
    - blinker==1.4
    - flask-assets==0.12
    - flask-bcrypt==0.7.*
    - flask-cache==0.13.1
    - flask-debugtoolbar==0.10.1
    - flask-ext==0.1
    - flask-mail==0.9.*
    - flask-migrate==2.5.*
    - flask-session==0.3.*
    - flask-thumbnails==1.0.*
    - flask-transfer==0.1.*
    - flask-webtest==0.0.*
    - flask-wtf==0.14.2
    - infinity==1.4
    - intervals==0.8.*
    - pillow==6.2.*
    - text-unidecode==1.3
    - validators==0.14.1
    - webassets==0.12.1
    - wtforms-components==0.10.4
